"""
Kozbeyli Konagi - Complete Updated Restaurant Menu Data
Extracted from the latest menu PDF (Feb 2026)
"""

UPDATED_MENU_CATEGORIES = [
    {"key": "kahvalti", "name_tr": "Kahvalti", "name_en": "Breakfast", "icon": "utensils", "sort_order": 0},
    {"key": "ekstralar", "name_tr": "Ekstralar", "name_en": "Extras", "icon": "plus-circle", "sort_order": 1},
    {"key": "baslangic", "name_tr": "Baslangic & Paylasimliklar", "name_en": "Starters & Shareables", "icon": "salad", "sort_order": 2},
    {"key": "pizza_sandvic", "name_tr": "Tas Firin Pizza & Sandvic", "name_en": "Stone Oven Pizza & Sandwich", "icon": "pizza", "sort_order": 3},
    {"key": "peynir", "name_tr": "Peynir Tabagi", "name_en": "Cheese Platter", "icon": "cheese", "sort_order": 4},
    {"key": "ana_yemek", "name_tr": "Ana Yemek", "name_en": "Main Course", "icon": "flame", "sort_order": 5},
    {"key": "ara_sicak", "name_tr": "Ara Sicaklar", "name_en": "Side Dishes", "icon": "soup", "sort_order": 6},
    {"key": "meze", "name_tr": "Mezeler", "name_en": "Meze", "icon": "leaf", "sort_order": 7},
    {"key": "tatli", "name_tr": "Tatlilar", "name_en": "Desserts", "icon": "cake", "sort_order": 8},
    {"key": "sicak_icecekler", "name_tr": "Sicak Icecekler", "name_en": "Hot Drinks", "icon": "coffee", "sort_order": 9},
    {"key": "soguk_icecekler", "name_tr": "Soguk Icecekler", "name_en": "Cold Drinks", "icon": "glass-water", "sort_order": 10},
    {"key": "sarap", "name_tr": "Saraplar", "name_en": "Wines", "icon": "wine", "sort_order": 11},
    {"key": "kokteyl", "name_tr": "Kokteyller", "name_en": "Cocktails", "icon": "cocktail", "sort_order": 12},
    {"key": "bira", "name_tr": "Biralar", "name_en": "Beers", "icon": "beer", "sort_order": 13},
    {"key": "viski", "name_tr": "Viskiler", "name_en": "Whiskies", "icon": "whiskey", "sort_order": 14},
    {"key": "raki", "name_tr": "Raki", "name_en": "Raki", "icon": "glass", "sort_order": 15},
]

UPDATED_MENU_ITEMS = {
    "kahvalti": [
        {"name": "Gurme Serpme Kahvalti", "price_try": 750, "desc": "Sahanda tereyagli sucuklu yumurta, domates, salatalik, yesil biber, roka, avokado, siyah zeytin, cesitli peynirler, ceviz ve mevsim meyveleri."},
        {"name": "Pisi Kahvalti Tabagi", "price_try": 750, "desc": "2 adet sicak pisi, beyaz peynir, tulum peynir, zeytinler, acili ezme, recel, salatalik ve domates."},
        {"name": "Sahanda Sucuklu Yumurta", "price_try": 400, "desc": "Sucuk dilimleri ve yumurta, tavada tereyagi ile pisirilerek servis edilir."},
        {"name": "Sahanda Peynirli Yumurta", "price_try": 300, "desc": "Yumurta ve peynirin tavada birlestigi lezzetli bir kahvalti."},
        {"name": "Sahanda Menemen", "price_try": 300, "desc": "Domates, biber ve yumurta ile hazirlanan geleneksel Turk kahvalti lezzeti."},
        {"name": "Sigara Boregi (4 Adet)", "price_try": 300, "desc": "Ince yufkaya sarilan, kizartilmis peynirli hafif atistirmalik."},
    ],
    "ekstralar": [
        {"name": "Fransiz Tereyagli Kruvasan (2 Adet)", "price_try": 300, "desc": "Kat kat acilan hamurun tereyagi ile harmanlanmasiyla yapilan klasik fransiz kruvasan."},
        {"name": "Cikolata Kremasi", "price_try": 80, "desc": "Findik ve kakao bazli kremali surulebiIir tatli."},
        {"name": "Dulce De Leche", "price_try": 100, "desc": "Tatli ve yogun kremamsi sos, karamelize sut tadiyla one cikar."},
        {"name": "Feslegenli Domatesli Ciabatta (4 Adet)", "price_try": 300, "desc": "Italya kokenli ciabatta ekmegi feslegen ve domatesle aromalandirilarak sunulur."},
        {"name": "Kare Rustik Ekmek", "price_try": 300, "desc": "Kare seklinde hazirlanmis rustik ekmek, geleneksel yontemle mayalanir."},
        {"name": "Mihlama", "price_try": 400, "desc": "Karadeniz mutfaginin unlu misir unu ve peynirle hazirlanan sicak yemegi."},
        {"name": "Omlet (Sade/Peynirli)", "price_try": 300, "desc": "Yumurta bazli, tercihe gore peynir eklenen kahvalti klasigi."},
        {"name": "Patates Kizartmasi", "price_try": 350, "desc": "Taze patates dilimleri, istege gore baharatli veya sade servis edilir."},
        {"name": "Pisi (Adet)", "price_try": 100, "desc": "Kizartilmis hamur, sicak servis edilir."},
    ],
    "baslangic": [
        {"name": "Baslangic Tabagi (2 Kisi)", "price_try": 350, "desc": "Zeytin, zahter, zeytinyagi ve feslegenli domatesli ciabatta."},
        {"name": "Roka Salatasi", "price_try": 400, "desc": "Roka, beyaz peynir, tarla domatesi, kuru incir, ceviz, balsamik glaze."},
        {"name": "Rustik Ekmek Ustu Fume Somon", "price_try": 500, "desc": "Fume somon parcalari rustik ekmek uzerinde sunulur."},
        {"name": "Kasap Sosis ve Patates Kizartmasi (2 Adet)", "price_try": 600, "desc": "Izgara sosis ve citir patates kizartmasi."},
        {"name": "Kizarmis Tavuk ve Baharatli Patates", "price_try": 600, "desc": "Tavuk parcalari kizartilip baharatlanir, patates kizartmasi esliginde."},
        {"name": "Patates Kizartmasi", "price_try": 350, "desc": "Taze patateslerden kizartilmis, baharatli veya sade."},
    ],
    "pizza_sandvic": [
        {"name": "Tas Firin Karisik Pizza", "price_try": 750, "desc": "Tas firinda pisirilmis, roka, parmesan ve acili zeytinyagi ile sunulur."},
        {"name": "Tas Firin Margarita Pizza", "price_try": 700, "desc": "Tas firinda pisirilmis, taze roka, parmesan peyniri ve acili zeytinyagi."},
        {"name": "Fume Dana Kaburga Pizza", "price_try": 1000, "desc": "Ince citir taban, eriyen mozarella, fume kaburga et dilimleri ve taze roka."},
        {"name": "Prosciutto Burrata Pizza", "price_try": 900, "desc": "Mozarella, hindi fume et dilimleri, taze roka, parmesan ile."},
        {"name": "Gurme Rustik Pesto Sandvic", "price_try": 600, "desc": "Rustik baget, beyaz peynir, domates, roka, pesto sosu. Patates kizartmasi esliginde."},
        {"name": "Dana Kaburga Fume Etli Sandvic", "price_try": 750, "desc": "Rustik baget ekmeGinde dana kaburga fume et, beyaz peynir, domates ve yesillik."},
        {"name": "Hindi Fume Etli Sandvic", "price_try": 750, "desc": "Rustik baget ekmeGinde hindi fume et, beyaz peynir, domates ve yesillik."},
    ],
    "peynir": [
        {"name": "Raki Eslikcisi Peynir Tabagi", "price_try": 1000, "desc": "Raki ile uyum saglayan cesitli peynir turlerinden olusan bir tabak."},
        {"name": "Turk Yerli Peynir Sarap Tabagi", "price_try": 1000, "desc": "Cesitli yerli peynirlerin bir araya geldigi, sarapla uyumlu zengin bir tabak."},
    ],
    "ana_yemek": [
        {"name": "Dallas Steak", "price_try": 3500, "desc": "Izgara izleriyle sulu, orta pismis antrikot, altin rengi patates puresi esliginde."},
        {"name": "Izgara Pirzola", "price_try": 1200, "desc": "Izgarada pisirilen kemikli et dilimleri, patates puresi ve kavrulmus file badem."},
        {"name": "Konak Kofte", "price_try": 800, "desc": "Geleneksel tarifle hazirlanan kofte, patates puresi ve kavrulmus file badem."},
        {"name": "Konak Sac Kavurma", "price_try": 1000, "desc": "Sacda pisirilen lezzetli et parcalari, patates puresi esliginde."},
        {"name": "Lokum Bonfile", "price_try": 1500, "desc": "Yumusacik biftek, patates puresi tabani uzerinde sunulur."},
    ],
    "ara_sicak": [
        {"name": "Icli Kofte", "price_try": 200, "desc": "Bulgurdan hazirlanan dis hamur, ici kiymali, kizartilarak servis edilir."},
        {"name": "Kasarli Mantar", "price_try": 450, "desc": "Taze mantarlar uzerine kasar peyniri serpilerek firinlanir."},
        {"name": "Pacanga Boregi", "price_try": 200, "desc": "Pastirma ve peynirle doldurulmus, ince yufkayla sarili kizartma borek."},
        {"name": "Somon Havyari", "price_try": 3000, "desc": "Parlak turuncu somon havyari taneleri buz uzerinde tazeligi korunarak sunulur."},
        {"name": "Tereyagli Pastirmali Antakya Humus", "price_try": 450, "desc": "Nohut-tahin humusu, uzerinde tereyagli pastirma ile servis edilir."},
    ],
    "meze": [
        {"name": "Acili Atom", "price_try": 300, "desc": "Yogurt ve aci biberle hazirlanan meze."},
        {"name": "Avokadolu Kapya Biber", "price_try": 350, "desc": "Avokado ve kapya biberin taze birlesimi, hafif ve renkli."},
        {"name": "Baslangic Tabagi (2 Kisi)", "price_try": 350, "desc": "Zeytin, zeytinyagi ve zahter ile rustik ekmek esliginde."},
        {"name": "Deniz Borulcesi", "price_try": 300, "desc": "Zeytinyagi ve limonla tatlandirilmis Ege mezesi."},
        {"name": "Feslegenli Girit Ezme", "price_try": 300, "desc": "Taze feslegen ve peynir bazli karisimla hazirlanan Girit ezmesi."},
        {"name": "Haydari", "price_try": 300, "desc": "Suzme yogurt ve taze otlarla klasik Turk mezesi."},
        {"name": "Kuru Cacik", "price_try": 300, "desc": "Yogurt ve salatalik esasli koyu kivamli meze."},
        {"name": "La Pena (Acili)", "price_try": 300, "desc": "Baharatli ve aci sevenlere hitap eden ozel meze."},
        {"name": "Yogurtlu Havuc Tarator", "price_try": 300, "desc": "Rendelenmis havuc ve yogurdun lezzetli birlesimi."},
        {"name": "Yogurtlu Patlican", "price_try": 300, "desc": "Kozlenmis patlican ile yogurt."},
        {"name": "Zeytinyagli Domatesli Humus", "price_try": 300, "desc": "Nohut ve tahin temelli humusun domates ve zeytinyagiyla zenginlestirilmis hali."},
        {"name": "Zeytinyagli Visneli Yaprak Sarma", "price_try": 350, "desc": "Asma yapraklarinda pirinc icini visnenin eksi tadiyla bulusturur."},
    ],
    "tatli": [
        {"name": "Antakya Kunefe", "price_try": 400, "desc": "Tel kadayif arasinda eriyen peynir ve serbet, fistik ve kaymak."},
        {"name": "Antep Fistikli Katmer", "price_try": 400, "desc": "Ince yufka, bol Antep fistigi, vanilyali Maras dondurma ile servis edilir."},
        {"name": "Churros", "price_try": 400, "desc": "Kizartilmis hamur cubuklari, cilek/visne receli veya Nutella ile."},
        {"name": "Cikolatali Mini Berliner (2 Adet)", "price_try": 300, "desc": "Mini cikolatali berliner, cikolata sosuyla kapli."},
        {"name": "Fransiz Tereyagli Kruvasan (Sade)", "price_try": 300, "desc": "Citir kruvasan, file bademlerle. Recel veya Nutella ile."},
        {"name": "Vanilyali Maras Dondurma (2 Top)", "price_try": 200, "desc": "Klasik vanilya lezzetiyle iki top dondurma."},
    ],
    "sicak_icecekler": [
        {"name": "Cay", "price_try": 40, "desc": "Geleneksel Turk cayi."},
        {"name": "Turk Kahvesi", "price_try": 150, "desc": "Esssiz telvesi, kopugu ve kadifemsi lezzetiyle."},
        {"name": "Americano", "price_try": 150, "desc": "Espresso ve sicak suyun birlesimi."},
        {"name": "Espresso", "price_try": 150, "desc": "Yogun ve sert kahve."},
        {"name": "Filtre Kahve", "price_try": 150, "desc": "Klasik yontemle demlenen kahve."},
        {"name": "Nescafe", "price_try": 150, "desc": "Hazir kahve, sut veya sekerle."},
        {"name": "Bitki Caylari", "price_try": 150, "desc": "Bitkisel karisimlardan olusan sicak cay."},
    ],
    "soguk_icecekler": [
        {"name": "Ice Latte", "price_try": 180, "desc": "Buzlu ve sutlu espresso karisimi."},
        {"name": "Ice Americano", "price_try": 180, "desc": "Buzla sogutulmus espresso bazli kahve."},
        {"name": "Taze Portakal Suyu", "price_try": 250, "desc": "Taze sikma, bol vitaminli."},
        {"name": "Kola", "price_try": 150, "desc": ""},
        {"name": "Fanta", "price_try": 150, "desc": ""},
        {"name": "Ice Tea", "price_try": 150, "desc": ""},
        {"name": "Nigde Gazozu", "price_try": 100, "desc": "Geleneksel meyve aromali gazoz."},
        {"name": "Soda", "price_try": 100, "desc": ""},
    ],
    "sarap": [
        {"name": "Phokaia Karasi (Kirmizi) 70cl", "price_try": 2000, "desc": "Aromatik kirmizi sarap."},
        {"name": "Phokaia Foca Karasi-Merlot 70cl", "price_try": 2000, "desc": "Merlot ve Foca karasi harmani."},
        {"name": "Phokaia Blend (Kirmizi) 70cl", "price_try": 2000, "desc": "Farkli uzum cesitlerinin ozenle harmanlandi kirmizi sarap."},
        {"name": "Okuzgozu 1970 (Kirmizi) 70cl", "price_try": 2000, "desc": "Uzun yillandirma sonucu kompleks tat profili."},
        {"name": "Okuzgozu 1970 (Kirmizi) Kadeh", "price_try": 500, "desc": "Yogun govde, yuvarlak aromalar."},
        {"name": "Phokaia Chardonnay (Beyaz) 70cl", "price_try": 2000, "desc": "Yumusak ve meyvemsi karakter, canli asidite."},
    ],
    "kokteyl": [
        {"name": "Kuzu Kulagi", "price_try": 600, "desc": "Tazeleyici kokteyl, eksimsi notalara sahip bitkisel tatlar."},
        {"name": "Wild Berry", "price_try": 600, "desc": "Tatli ve hafif eksi meyve ozleri."},
    ],
    "bira": [
        {"name": "Blanc", "price_try": 275, "desc": "Narenciye ve hafif baharat notali."},
        {"name": "Carlsberg", "price_try": 250, "desc": "Hafif icimli klasik bira."},
        {"name": "Tuborg Gold", "price_try": 250, "desc": "Orta govdeli, hafif tatlimsi."},
    ],
    "viski": [
        {"name": "Jack Daniels (Tek)", "price_try": 500, "desc": "Klasik Amerikan viski, karamel ve vanilya notalari."},
        {"name": "Jack Daniels (Duble)", "price_try": 800, "desc": "Tennessee viski, zengin karamel ve odunsu nuanslar."},
        {"name": "Jack Daniels 35cl", "price_try": 2500, "desc": ""},
        {"name": "Jack Daniels 70cl", "price_try": 4300, "desc": ""},
        {"name": "Chivas Regal (Tek)", "price_try": 600, "desc": "Yumusak Iskoc harman viski, tatli malt notalari."},
        {"name": "Chivas Regal (Duble)", "price_try": 1000, "desc": "Zengin tahil ve meyve tonlari."},
        {"name": "Chivas Regal 35cl", "price_try": 2500, "desc": ""},
        {"name": "Chivas Regal 70cl", "price_try": 4300, "desc": ""},
        {"name": "Woodford Reserve (Tek)", "price_try": 800, "desc": "Amerikan burbonu, karamel, vanilya ve mese tonlari."},
        {"name": "Woodford Reserve (Duble)", "price_try": 1200, "desc": "Mese ficilarinda yillandirilmis kompleks tat profili."},
        {"name": "Woodford Reserve 70cl", "price_try": 5000, "desc": ""},
    ],
    "raki": [
        {"name": "Beylerbeyi Gobek (Tek)", "price_try": 500, "desc": "Geleneksel anason aromasi."},
        {"name": "Beylerbeyi Gobek (Duble)", "price_try": 600, "desc": "Tatlilik ve anason dengesi."},
        {"name": "Beylerbeyi Gobek 35cl", "price_try": 2150, "desc": ""},
        {"name": "Beylerbeyi Gobek 50cl", "price_try": 2650, "desc": ""},
        {"name": "Beylerbeyi Gobek 70cl", "price_try": 3400, "desc": ""},
    ],
}
